# Generated by Django 4.2 on 2023-07-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
