# Generated by Django 4.2.1 on 2023-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='portada'),
        ),
    ]
